import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeroUIProvider } from "@heroui/react";
import "./globals.css";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 解决hydration warning  和浏览器插件冲突报错
    <html lang="en" suppressHydrationWarning={true}> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
        <HeroUIProvider>
          <Header />
          <div className="max-w-[1024px] px-6 mt-5 mx-auto">         
          {/* <div className="z-40 flex px-6 gap-4 w-full flex-row relative flex-nowrap items-center justify-between h-[var(--navbar-height)] max-w-[1024px]"> */}
          {children}
          </div>
        </HeroUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
